# Generated by Django 5.2.11 on 2026-03-07 15:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account_code', models.CharField(max_length=64, unique=True, verbose_name='账户编号')),
                ('account_name', models.CharField(max_length=128, verbose_name='账户名称')),
                ('account_type', models.CharField(choices=[('普通账户', '普通账户'), ('融资账户', '融资账户'), ('期权账户', '期权账户')], max_length=16, verbose_name='账户类型')),
                ('base_currency', models.CharField(choices=[('CNY', 'CNY'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=8, verbose_name='基础币种')),
                ('broker_name', models.CharField(blank=True, max_length=128, verbose_name='券商名称')),
                ('initial_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='初始资金')),
                ('available_cash', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='可用资金')),
                ('status', models.CharField(choices=[('启用', '启用'), ('停用', '停用')], default='启用', max_length=16, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'db_table': 'accounts',
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('symbol', models.CharField(max_length=32, verbose_name='标的代码')),
                ('name', models.CharField(max_length=128, verbose_name='标的名称')),
                ('market', models.CharField(choices=[('CN', 'CN'), ('HK', 'HK'), ('US', 'US'), ('MACRO', 'MACRO')], max_length=16, verbose_name='市场')),
                ('exchange', models.CharField(choices=[('SSE', 'SSE'), ('SZSE', 'SZSE'), ('BSE', 'BSE'), ('HKEX', 'HKEX'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE'), ('OTC', 'OTC')], max_length=16, verbose_name='交易所')),
                ('instrument_type', models.CharField(choices=[('股票', '股票'), ('ETF', 'ETF'), ('指数', '指数'), ('外汇', '外汇'), ('利率', '利率')], max_length=16, verbose_name='标的类型')),
                ('trading_currency', models.CharField(choices=[('CNY', 'CNY'), ('HKD', 'HKD'), ('USD', 'USD'), ('CNH', 'CNH')], max_length=8, verbose_name='交易币种')),
                ('lot_size', models.PositiveIntegerField(default=1, verbose_name='最小交易单位')),
                ('tick_size', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='最小变动价位')),
                ('tradable', models.BooleanField(default=True, verbose_name='可交易')),
                ('status', models.CharField(choices=[('启用', '启用'), ('停用', '停用')], default='启用', max_length=16, verbose_name='状态')),
                ('data_source', models.CharField(blank=True, max_length=64, verbose_name='数据源')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '标的',
                'verbose_name_plural': '标的',
                'db_table': 'instruments',
                'ordering': ['market', 'symbol'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'market'), name='uniq_instrument_symbol_market')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('side', models.CharField(choices=[('做多', '做多'), ('做空', '做空')], default='做多', max_length=8, verbose_name='方向')),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='持仓数量')),
                ('available_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='可用数量')),
                ('average_price', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='持仓均价')),
                ('cost_basis', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='持仓成本')),
                ('market_value', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='持仓市值')),
                ('unrealized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='未实现盈亏')),
                ('pricing_currency', models.CharField(choices=[('CNY', 'CNY'), ('HKD', 'HKD'), ('USD', 'USD'), ('CNH', 'CNH')], max_length=8, verbose_name='计价币种')),
                ('status', models.CharField(choices=[('持有中', '持有中'), ('已平仓', '已平仓')], default='持有中', max_length=16, verbose_name='状态')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='建仓时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='平仓时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trader.account', verbose_name='账户')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trader.instrument', verbose_name='标的')),
            ],
            options={
                'verbose_name': '持仓',
                'verbose_name_plural': '持仓',
                'db_table': 'positions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fill_time', models.DateTimeField(verbose_name='成交时间')),
                ('side', models.CharField(choices=[('买入', '买入'), ('卖出', '卖出')], max_length=8, verbose_name='买卖方向')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-08)], verbose_name='成交数量')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='成交价格')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='成交金额')),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='手续费')),
                ('tax', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='税费')),
                ('pricing_currency', models.CharField(choices=[('CNY', 'CNY'), ('HKD', 'HKD'), ('USD', 'USD'), ('CNH', 'CNH')], max_length=8, verbose_name='计价币种')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='外部成交编号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='trader.account', verbose_name='账户')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='trader.instrument', verbose_name='标的')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fills', to='trader.position', verbose_name='关联持仓')),
            ],
            options={
                'verbose_name': '成交',
                'verbose_name_plural': '成交',
                'db_table': 'fills',
                'ordering': ['-fill_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bar_type', models.CharField(choices=[('spot', '现价'), ('1m', '1分钟'), ('1d', '日线')], default='spot', max_length=8, verbose_name='价格类型')),
                ('priced_at', models.DateTimeField(verbose_name='价格时间')),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='开盘价')),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='最高价')),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='最低价')),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='收盘价')),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='最新价')),
                ('prev_close', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='昨收价')),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='成交量')),
                ('turnover', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='成交额')),
                ('source', models.CharField(blank=True, max_length=64, verbose_name='数据来源')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='trader.instrument', verbose_name='标的')),
            ],
            options={
                'verbose_name': '标的价格',
                'verbose_name_plural': '标的价格',
                'db_table': 'instrument_prices',
                'ordering': ['-priced_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'bar_type', 'priced_at'), name='uniq_instrument_price_bar_time')],
            },
        ),
    ]
