# Generated by Django 5.2.11 on 2026-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table_name', models.CharField(max_length=128, verbose_name='表名')),
                ('record_pk', models.CharField(max_length=64, verbose_name='记录主键')),
                ('operation', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('rollback', '回滚')], max_length=16, verbose_name='操作类型')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='变更前数据')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='变更后数据')),
                ('actor', models.CharField(blank=True, max_length=64, verbose_name='操作人')),
                ('source', models.CharField(blank=True, max_length=128, verbose_name='来源')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
