# Generated by Django 5.2.11 on 2026-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_equity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='账户总资产'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_market_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='持仓市值'),
        ),
        migrations.AddField(
            model_name='account',
            name='total_unrealized_pnl',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='未实现盈亏'),
        ),
    ]
