# Generated by Django 5.2.11 on 2026-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_account_total_equity_account_total_market_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='frozen_cash',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='冻结资金'),
        ),
        migrations.AddField(
            model_name='account',
            name='liability',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='负债'),
        ),
        migrations.AddField(
            model_name='account',
            name='risk_limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='风险限额'),
        ),
    ]
