# Generated by Django 5.2.11 on 2026-03-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_account_frozen_cash_account_liability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report_date', models.DateField(unique=True, verbose_name='报告日期')),
                ('reported_at', models.DateTimeField(verbose_name='生成时间')),
                ('quote_count', models.PositiveIntegerField(default=0, verbose_name='标的数量')),
                ('ok_count', models.PositiveIntegerField(default=0, verbose_name='正常数量')),
                ('missing_instrument_count', models.PositiveIntegerField(default=0, verbose_name='缺少标的数量')),
                ('missing_price_count', models.PositiveIntegerField(default=0, verbose_name='缺少价格数量')),
            ],
            options={
                'verbose_name': '每日市场快照',
                'verbose_name_plural': '每日市场快照',
                'db_table': 'daily_market_snapshots',
                'ordering': ['-report_date', '-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMarketQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=64, verbose_name='配置键')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('symbol', models.CharField(max_length=32, verbose_name='代码')),
                ('market', models.CharField(max_length=16, verbose_name='市场')),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='现价')),
                ('prev_close', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='昨收')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='涨跌幅')),
                ('priced_at', models.DateTimeField(blank=True, null=True, verbose_name='价格时间')),
                ('source', models.CharField(blank=True, max_length=64, verbose_name='来源')),
                ('status', models.CharField(choices=[('ok', '正常'), ('missing_instrument', '缺少标的'), ('missing_price', '缺少价格')], max_length=32, verbose_name='状态')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_market_quotes', to='trader.instrument', verbose_name='标的')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='trader.dailymarketsnapshot', verbose_name='市场快照')),
            ],
            options={
                'verbose_name': '每日市场行情明细',
                'verbose_name_plural': '每日市场行情明细',
                'db_table': 'daily_market_quotes',
                'ordering': ['snapshot_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'key'), name='uniq_daily_market_quote_snapshot_key')],
            },
        ),
        migrations.CreateModel(
            name='DailyMarketIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('indicator_key', models.CharField(choices=[('300_vs_2000', '沪深300对中证2000'), ('sh_vs_chinext', '上证核心对创业板'), ('sh_vs_hstech', '上证核心对恒科')], max_length=32, verbose_name='指标键')),
                ('title', models.CharField(max_length=64, verbose_name='指标标题')),
                ('left_key', models.CharField(blank=True, max_length=64, verbose_name='左侧配置键')),
                ('right_key', models.CharField(blank=True, max_length=64, verbose_name='右侧配置键')),
                ('left_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='左侧值')),
                ('right_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='右侧值')),
                ('diff_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='差值')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='分类结果')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='trader.dailymarketsnapshot', verbose_name='市场快照')),
            ],
            options={
                'verbose_name': '每日市场指标',
                'verbose_name_plural': '每日市场指标',
                'db_table': 'daily_market_indicators',
                'ordering': ['snapshot_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'indicator_key'), name='uniq_daily_market_indicator_snapshot_key')],
            },
        ),
    ]
