# Generated by Django 5.2.11 on 2026-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_dailymarketsnapshot_dailymarketquote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymarketquote',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='dailymarketquote',
            name='snapshot',
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='bse_50_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='北证50涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='bse_50_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='北证50现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='bse_50_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='北证50昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='bse_50_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='北证50价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='bse_50_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='北证50来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='bse_50_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='北证50状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='chinext_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='创业板指涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='chinext_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='创业板指现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='chinext_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='创业板指昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='chinext_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创业板指价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='chinext_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='创业板指来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='chinext_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='创业板指状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='cn10y_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CN10Y涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='cn10y_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='CN10Y现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='cn10y_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='CN10Y昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='cn10y_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CN10Y价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='cn10y_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='CN10Y来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='cn10y_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='CN10Y状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='csi_2000_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='中证2000涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='csi_2000_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='中证2000现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='csi_2000_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='中证2000昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='csi_2000_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='中证2000价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='csi_2000_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='中证2000来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='csi_2000_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='中证2000状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hkdcnh_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='HKDCNH涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hkdcnh_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='HKDCNH现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hkdcnh_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='HKDCNH昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hkdcnh_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='HKDCNH价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hkdcnh_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='HKDCNH来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hkdcnh_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='HKDCNH状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hstech_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='恒生科技涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hstech_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='恒生科技现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hstech_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='恒生科技昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hstech_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='恒生科技价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hstech_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='恒生科技来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='hstech_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='恒生科技状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_1000_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='中证1000涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_1000_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='中证1000现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_1000_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='中证1000昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_1000_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='中证1000价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_1000_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='中证1000来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_1000_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='中证1000状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_300_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='沪深300涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_300_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='沪深300现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_300_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='沪深300昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_300_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='沪深300价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_300_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='沪深300来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_300_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='沪深300状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_50_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='上证50涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_50_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='上证50现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_50_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='上证50昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_50_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上证50价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_50_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='上证50来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='index_50_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='上证50状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_300_vs_2000_category',
            field=models.CharField(blank=True, max_length=64, verbose_name='300对2000分类'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_300_vs_2000_diff_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='300对2000差值'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_300_vs_2000_left_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='300对2000左值'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_300_vs_2000_right_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='300对2000右值'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_300_vs_2000_summary',
            field=models.TextField(blank=True, verbose_name='300对2000摘要'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_chinext_category',
            field=models.CharField(blank=True, max_length=64, verbose_name='上证对创业板分类'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_chinext_diff_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='上证对创业板差值'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_chinext_left_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='上证对创业板左值'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_chinext_right_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='上证对创业板右值'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_chinext_summary',
            field=models.TextField(blank=True, verbose_name='上证对创业板摘要'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_hstech_category',
            field=models.CharField(blank=True, max_length=64, verbose_name='上证对恒科分类'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_hstech_diff_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='上证对恒科差值'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_hstech_left_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='上证对恒科左值'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_hstech_right_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='上证对恒科右值'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='indicator_sh_vs_hstech_summary',
            field=models.TextField(blank=True, verbose_name='上证对恒科摘要'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='securities_881157_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='证券881157涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='securities_881157_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='证券881157现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='securities_881157_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='证券881157昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='securities_881157_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='证券881157价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='securities_881157_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='证券881157来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='securities_881157_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='证券881157状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='star_50_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='科创50涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='star_50_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='科创50现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='star_50_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='科创50昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='star_50_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='科创50价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='star_50_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='科创50来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='star_50_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='科创50状态'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='usdcnh_change_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='USDCNH涨跌幅'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='usdcnh_last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='USDCNH现价'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='usdcnh_prev_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='USDCNH昨收'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='usdcnh_priced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='USDCNH价格时间'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='usdcnh_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='USDCNH来源'),
        ),
        migrations.AddField(
            model_name='dailymarketsnapshot',
            name='usdcnh_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='USDCNH状态'),
        ),
        migrations.DeleteModel(
            name='DailyMarketIndicator',
        ),
        migrations.DeleteModel(
            name='DailyMarketQuote',
        ),
    ]
