# Generated by Django 5.2.11 on 2026-03-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trader", "0006_remove_dailymarketquote_instrument_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyMarketSnapshot",
        ),
    ]
