# Generated by Codex on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trader", "0007_delete_dailymarketsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMarketReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("report_date", models.DateField(unique=True, verbose_name="报告日期")),
                ("reported_at", models.DateTimeField(verbose_name="生成时间")),
                ("hs300_sector_summary", models.TextField(blank=True, verbose_name="沪深300行业统计摘要")),
                ("markdown_content", models.TextField(blank=True, verbose_name="报告正文")),
            ],
            options={
                "verbose_name": "每日市场报告",
                "verbose_name_plural": "每日市场报告",
                "db_table": "daily_market_reports",
                "ordering": ["-report_date", "-id"],
            },
        ),
    ]
