# Generated by Django 5.2.11 on 2026-03-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_position_position_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_high_dividend',
            field=models.BooleanField(default=False, verbose_name='高股息标的'),
        ),
    ]
