# Generated by Django 5.2.11 on 2026-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_instrument_is_high_dividend'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentprice',
            name='annual_cash_dividend_per_10',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='年报分红(每10股)'),
        ),
        migrations.AddField(
            model_name='instrumentprice',
            name='annual_dividend_per_share',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='年报每股分红'),
        ),
        migrations.AddField(
            model_name='instrumentprice',
            name='annual_dividend_report',
            field=models.CharField(blank=True, max_length=32, verbose_name='年报报告期'),
        ),
        migrations.AddField(
            model_name='instrumentprice',
            name='annual_dividend_yield_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='年报股息率(%)'),
        ),
    ]
